/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  CardOperationsApi,
  CustomFormsApi,
  CvvOperationsApi,
  NetworkTokenApi,
  PaymentGatewayApi,
  PaymentGatewayAccountsApi,
  StringTokensApi,
  ThreeDsMerchantsApi,
  ThreeDsSessionsApi,
  ToolsApi,
  UtilsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BlueTimeCustom } from "./client-custom";

export class BlueTime extends BlueTimeCustom {
  readonly cardOperations: CardOperationsApi;
  readonly customForms: CustomFormsApi;
  readonly cvvOperations: CvvOperationsApi;
  readonly networkToken: NetworkTokenApi;
  readonly paymentGateway: PaymentGatewayApi;
  readonly paymentGatewayAccounts: PaymentGatewayAccountsApi;
  readonly stringTokens: StringTokensApi;
  readonly threeDsMerchants: ThreeDsMerchantsApi;
  readonly threeDsSessions: ThreeDsSessionsApi;
  readonly tools: ToolsApi;
  readonly utils: UtilsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.cardOperations = new CardOperationsApi(configuration);
    this.customForms = new CustomFormsApi(configuration);
    this.cvvOperations = new CvvOperationsApi(configuration);
    this.networkToken = new NetworkTokenApi(configuration);
    this.paymentGateway = new PaymentGatewayApi(configuration);
    this.paymentGatewayAccounts = new PaymentGatewayAccountsApi(configuration);
    this.stringTokens = new StringTokensApi(configuration);
    this.threeDsMerchants = new ThreeDsMerchantsApi(configuration);
    this.threeDsSessions = new ThreeDsSessionsApi(configuration);
    this.tools = new ToolsApi(configuration);
    this.utils = new UtilsApi(configuration);
  }

}
