/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomFormsUploadFormFolderRequest
 */
export interface CustomFormsUploadFormFolderRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomFormsUploadFormFolderRequest
     */
    'ContentType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFormsUploadFormFolderRequest
     */
    'ContentDisposition'?: string;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof CustomFormsUploadFormFolderRequest
     */
    'Headers'?: { [key: string]: Array<string>; };
    /**
     * 
     * @type {number}
     * @memberof CustomFormsUploadFormFolderRequest
     */
    'Length'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomFormsUploadFormFolderRequest
     */
    'Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomFormsUploadFormFolderRequest
     */
    'FileName'?: string;
}

