/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e } from './system-collections-generic-key-value-pair2-system-string-system-private-core-lib-version6000-cultureneutral-public-key-token7cec85d7bea7798e-system-string-system-private-core-lib-version6000-cultureneutral-public-key-token7cec85d7bea7798e';

/**
 * Input Model for designating a payment gateway account
 * @export
 * @interface PayToolsApiModelsPaymentGatewayAccountInputModel
 */
export interface PayToolsApiModelsPaymentGatewayAccountInputModel {
    /**
     * Unique name of the Payment Gateway the account information relates to.
     * @type {string}
     * @memberof PayToolsApiModelsPaymentGatewayAccountInputModel
     */
    'paymentGatewayName'?: string | null;
    /**
     * A list of key-value pairs that represents your credentials within the Payment gateway.   Each key should represent a parameter listed in the \"CredentialsNames\" element of the response from the list all payment gateways method at `[GET] /paymentGateway`  Example:  \"Credentials\": [     {         \"Key\": \"PrivateKey\",         \"Value\": \"VBtt666M/G098098vgdewvk0Mc-GH\"     }  ]
     * @type {Array<SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e>}
     * @memberof PayToolsApiModelsPaymentGatewayAccountInputModel
     */
    'credentials'?: Array<SystemCollectionsGenericKeyValuePair2SystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798eSystemStringSystemPrivateCoreLibVersion6000CultureneutralPublicKeyToken7cec85d7bea7798e> | null;
}

