/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The billing information of the card owner to be used for validation
 * @export
 * @interface PayToolsApiModelsPayerBase
 */
export interface PayToolsApiModelsPayerBase {
    /**
     * City
     * @type {string}
     * @memberof PayToolsApiModelsPayerBase
     */
    'city'?: string | null;
    /**
     * State or Province
     * @type {string}
     * @memberof PayToolsApiModelsPayerBase
     */
    'stateProvince'?: string | null;
    /**
     * 2 letter country code (<a href=\"https://en.wikipedia.org/wiki/ISO_3166-2#Current_codes\" target=\"_blank\">ISO 3166-2 <img src=\"https://files.readme.io/b676144-openNewWindow.png\" width=\"10\" /></a>)
     * @type {string}
     * @memberof PayToolsApiModelsPayerBase
     */
    'countryCode': string;
}

