/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsApiModelsCardInputModel } from './pay-tools-api-models-card-input-model';
import { PayToolsApiModelsPayerDetails } from './pay-tools-api-models-payer-details';
import { PayToolsApiModelsPaymentGatewayAccount } from './pay-tools-api-models-payment-gateway-account';
import { PaymentsNetworkTokenSchemes } from './payments-network-token-schemes';

/**
 * Model for a Charge/Pre-authorize request for card processing via a payment gateway
 * @export
 * @interface PayToolsApiModelsAuthRequestModel
 */
export interface PayToolsApiModelsAuthRequestModel {
    /**
     * The currency of the transaction. Based on the <a href=\"https://en.wikipedia.org/wiki/ISO_4217#Active_codes\" target=\"_blank\">ISO 4217</a> standard.
     * @type {string}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'currency': string;
    /**
     * This field is an additional optional parameter used by some of our payment processors. Please read our additional guidance section for payment processors that use this and other parameters
     * @type {boolean}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'isDigital'?: boolean;
    /**
     * This field is an additional optional parameter used by some of our payment processors. Please read our additional guidance section for payment processors that use this and other parameters
     * @type {string}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'orderDesc'?: string | null;
    /**
     * 
     * @type {PayToolsApiModelsPayerDetails}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'payerDetails'?: PayToolsApiModelsPayerDetails;
    /**
     * 
     * @type {PayToolsApiModelsCardInputModel}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'card': PayToolsApiModelsCardInputModel;
    /**
     * The amount to be charged (the amount should be in major units - for example, 10.23)
     * @type {number}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'amount': number;
    /**
     * Your custom reference for this transaction
     * @type {string}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'myRef'?: string | null;
    /**
     * The reference name provided to the stored Payment Gateway Account as set in `PUT /PaymentGatewayAccounts/{name}`.  **Please note**, if you provide us with both this parameter and the raw credentials in the `paymentGatewayAccount` object, this parameter will be ignored and the raw credentials will take precedence.
     * @type {string}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'paymentGatewayAccountName'?: string | null;
    /**
     * Optional parameter if the payment gateway requires authentication using a client certificate. The name of the certificate that was stored in our system via our <a href=\"https://portal.epaytools.com\" target=\"_blank\">users portal</a>
     * @type {string}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'certificateName'?: string | null;
    /**
     * 
     * @type {PayToolsApiModelsPaymentGatewayAccount}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'paymentGatewayAccount'?: PayToolsApiModelsPaymentGatewayAccount;
    /**
     * 
     * @type {PaymentsNetworkTokenSchemes}
     * @memberof PayToolsApiModelsAuthRequestModel
     */
    'networkTokenBrand'?: PaymentsNetworkTokenSchemes;
}

