/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsSharedModelsMessageType } from './pay-tools-shared-models-message-type';

/**
 * base class for message to client (Http response or over WebSocket)
 * @export
 * @interface PayToolsSharedModelsThreeDsClientMessage
 */
export interface PayToolsSharedModelsThreeDsClientMessage {
    /**
     * Client message type enumeration
     * @type {PayToolsSharedModelsMessageType}
     * @memberof PayToolsSharedModelsThreeDsClientMessage
     */
    'messageType'?: PayToolsSharedModelsMessageType;
}

