/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Tokenization Action
 * @export
 * @enum {string}
 */
export type PayToolsBlAuthenticationTokenizationAction = 'Always' | 'IfChargeSuccessful' | 'Never'

