/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentsCardTypes } from './payments-card-types';

/**
 * Base model for card with Card holder name and Card Type
 * @export
 * @interface PayToolsSharedModelsCardStoredCard
 */
export interface PayToolsSharedModelsCardStoredCard {
    /**
     * a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"
     * @type {string}
     * @memberof PayToolsSharedModelsCardStoredCard
     */
    'cardToken': string;
    /**
     * Expiration year
     * @type {number}
     * @memberof PayToolsSharedModelsCardStoredCard
     */
    'expirationYear': number;
    /**
     * Expiration year
     * @type {number}
     * @memberof PayToolsSharedModelsCardStoredCard
     */
    'expirationMonth': number;
    /**
     * 
     * @type {PaymentsCardTypes}
     * @memberof PayToolsSharedModelsCardStoredCard
     */
    'cardType'?: PaymentsCardTypes;
    /**
     * Cardholder name (as apears on card)
     * @type {string}
     * @memberof PayToolsSharedModelsCardStoredCard
     */
    'cardHolderName': string;
}

