/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for returning the url to an uploaded custom form
 * @export
 * @interface PayToolsApiModelsCustomFormUploadModel
 */
export interface PayToolsApiModelsCustomFormUploadModel {
    /**
     * The base url to an uploaded custom form
     * @type {string}
     * @memberof PayToolsApiModelsCustomFormUploadModel
     */
    'formBaseUrl'?: string | null;
}

