/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentsCardTypes } from './payments-card-types';

/**
 * A brand for 3DS authentication
 * @export
 * @interface PayToolsBlAuthenticationThreeDsBrand
 */
export interface PayToolsBlAuthenticationThreeDsBrand {
    /**
     * 
     * @type {PaymentsCardTypes}
     * @memberof PayToolsBlAuthenticationThreeDsBrand
     */
    'brd'?: PaymentsCardTypes;
    /**
     * Brand\'s Bin
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDsBrand
     */
    'bin': string;
    /**
     * Merchant Id
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDsBrand
     */
    'mid': string;
    /**
     * Brand\'s MCC
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDsBrand
     */
    'mcc': string;
}

