/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NetworkTokenRequestSource } from './network-token-request-source';
import { PaymentsNetworkTokenSchemes } from './payments-network-token-schemes';

/**
 * Network Tokenization Request
 * @export
 * @interface PayToolsApiModelsNetworkTokenizationDeleteTokenRequest
 */
export interface PayToolsApiModelsNetworkTokenizationDeleteTokenRequest {
    /**
     * 
     * @type {NetworkTokenRequestSource}
     * @memberof PayToolsApiModelsNetworkTokenizationDeleteTokenRequest
     */
    'source': NetworkTokenRequestSource;
    /**
     * 
     * @type {PaymentsNetworkTokenSchemes}
     * @memberof PayToolsApiModelsNetworkTokenizationDeleteTokenRequest
     */
    'brand'?: PaymentsNetworkTokenSchemes;
    /**
     * Token Id within the Brand
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationDeleteTokenRequest
     */
    'tokenId': string;
    /**
     * Reason for deletion
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationDeleteTokenRequest
     */
    'reason'?: string | null;
}

