/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsApiModelsStringTokenMetaDataOutputModel } from './pay-tools-api-models-string-token-meta-data-output-model';

/**
 * The model used to return a valid Jws with payload
 * @export
 * @interface PayToolsApiModelsJwsOutputModel1PayToolsApiModelsStringTokenMetaDataOutputModelPayToolsApiVersion10715CultureneutralPublicKeyTokennull
 */
export interface PayToolsApiModelsJwsOutputModel1PayToolsApiModelsStringTokenMetaDataOutputModelPayToolsApiVersion10715CultureneutralPublicKeyTokennull {
    /**
     * 
     * @type {PayToolsApiModelsStringTokenMetaDataOutputModel}
     * @memberof PayToolsApiModelsJwsOutputModel1PayToolsApiModelsStringTokenMetaDataOutputModelPayToolsApiVersion10715CultureneutralPublicKeyTokennull
     */
    'payload'?: PayToolsApiModelsStringTokenMetaDataOutputModel;
    /**
     * The jws (token) value to be used in subsequent card operation methods
     * @type {string}
     * @memberof PayToolsApiModelsJwsOutputModel1PayToolsApiModelsStringTokenMetaDataOutputModelPayToolsApiVersion10715CultureneutralPublicKeyTokennull
     */
    'authToken'?: string | null;
}

