/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsBlAuthenticationChargeCardSignedModel } from './pay-tools-bl-authentication-charge-card-signed-model';

/**
 * The model used to return a valid Jws with payload
 * @export
 * @interface PayToolsApiModelsJwsOutputModel1PayToolsBlAuthenticationChargeCardSignedModelPayToolsBlVersion1000CultureneutralPublicKeyTokennull
 */
export interface PayToolsApiModelsJwsOutputModel1PayToolsBlAuthenticationChargeCardSignedModelPayToolsBlVersion1000CultureneutralPublicKeyTokennull {
    /**
     * 
     * @type {PayToolsBlAuthenticationChargeCardSignedModel}
     * @memberof PayToolsApiModelsJwsOutputModel1PayToolsBlAuthenticationChargeCardSignedModelPayToolsBlVersion1000CultureneutralPublicKeyTokennull
     */
    'payload'?: PayToolsBlAuthenticationChargeCardSignedModel;
    /**
     * The jws (token) value to be used in subsequent card operation methods
     * @type {string}
     * @memberof PayToolsApiModelsJwsOutputModel1PayToolsBlAuthenticationChargeCardSignedModelPayToolsBlVersion1000CultureneutralPublicKeyTokennull
     */
    'authToken'?: string | null;
}

