/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsApiModelsThreeDSAuthenticationInputModel } from './pay-tools-api-models-three-dsauthentication-input-model';
import { PaymentsCardTypes } from './payments-card-types';

/**
 * The card details that should be charged. You can either provide us with the raw card details or provide a reference to the stored card details in a token.
 * @export
 * @interface PayToolsApiModelsCardInputModel
 */
export interface PayToolsApiModelsCardInputModel {
    /**
     * Card owner Id
     * @type {string}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'ownerID'?: string | null;
    /**
     * Card Issue Number
     * @type {string}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'issueNumber'?: string | null;
    /**
     * Card security code (digits on back of card)
     * @type {string}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'cvv'?: string | null;
    /**
     * 
     * @type {PayToolsApiModelsThreeDSAuthenticationInputModel}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'threeDSAuthentication'?: PayToolsApiModelsThreeDSAuthenticationInputModel;
    /**
     * 
     * @type {PaymentsCardTypes}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'cardType'?: PaymentsCardTypes;
    /**
     * Cardholder name (as apears on card)
     * @type {string}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'cardHolderName': string;
    /**
     * Card number (PAN) or a Reference to a Tokenized string. A Token should be referenced in the format @TOKEN, e.g \"@nQGywsQE9gbURtrXEjTZwtWqeMdK9nsO\"
     * @type {string}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'cardNumber': string;
    /**
     * Expiration year
     * @type {number}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'expirationYear': number;
    /**
     * Expiration month
     * @type {number}
     * @memberof PayToolsApiModelsCardInputModel
     */
    'expirationMonth': number;
}

