/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsBlAuthenticationChargePresetData } from './pay-tools-bl-authentication-charge-preset-data';
import { PayToolsBlAuthenticationThreeDsSessionModel } from './pay-tools-bl-authentication-three-ds-session-model';
import { PayToolsBlAuthenticationTokenizationAction } from './pay-tools-bl-authentication-tokenization-action';
import { PayToolsSharedEnumsPerform3ds } from './pay-tools-shared-enums-perform3ds';
import { PciBookingIINLookupLibraryRiskLevel } from './pci-booking-iinlookup-library-risk-level';

/**
 * Model for initial request for a Card operation session
 * @export
 * @interface PayToolsBlAuthenticationPreSignedDataModel
 */
export interface PayToolsBlAuthenticationPreSignedDataModel {
    /**
     * 
     * @type {PayToolsBlAuthenticationThreeDsSessionModel}
     * @memberof PayToolsBlAuthenticationPreSignedDataModel
     */
    'threeDsSessionModel'?: PayToolsBlAuthenticationThreeDsSessionModel;
    /**
     * 
     * @type {PciBookingIINLookupLibraryRiskLevel}
     * @memberof PayToolsBlAuthenticationPreSignedDataModel
     */
    'vld'?: PciBookingIINLookupLibraryRiskLevel;
    /**
     * Options for performing #DS
     * @type {PayToolsSharedEnumsPerform3ds}
     * @memberof PayToolsBlAuthenticationPreSignedDataModel
     */
    '3ds'?: PayToolsSharedEnumsPerform3ds;
    /**
     * Is Card charge required for this session
     * @type {boolean}
     * @memberof PayToolsBlAuthenticationPreSignedDataModel
     */
    'crg'?: boolean;
    /**
     * Tokenization Action
     * @type {PayToolsBlAuthenticationTokenizationAction}
     * @memberof PayToolsBlAuthenticationPreSignedDataModel
     */
    'tkn'?: PayToolsBlAuthenticationTokenizationAction;
    /**
     * 
     * @type {PayToolsBlAuthenticationChargePresetData}
     * @memberof PayToolsBlAuthenticationPreSignedDataModel
     */
    'crg_d'?: PayToolsBlAuthenticationChargePresetData;
}

