/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for accepting payer details for Network Tokenization
 * @export
 * @interface PayToolsApiModelsNetworkTokenizationPayer
 */
export interface PayToolsApiModelsNetworkTokenizationPayer {
    /**
     * Email address
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'email'?: string | null;
    /**
     * First Name
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'firstName': string;
    /**
     * Lasst Name
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'lastName': string;
    /**
     * Phone number
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'phone'?: string | null;
    /**
     * 1st address line
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'address1'?: string | null;
    /**
     * 2nd address line
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'address2'?: string | null;
    /**
     * 3rd address line
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'address3'?: string | null;
    /**
     * Postal code or Zip code
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'postCode'?: string | null;
    /**
     * Client IP address
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'clientIPAddress': string;
    /**
     * City
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'city'?: string | null;
    /**
     * State or Province
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'stateProvince'?: string | null;
    /**
     * 2 letter country code (<a href=\"https://en.wikipedia.org/wiki/ISO_3166-2#Current_codes\" target=\"_blank\">ISO 3166-2 <img src=\"https://files.readme.io/b676144-openNewWindow.png\" width=\"10\" /></a>)
     * @type {string}
     * @memberof PayToolsApiModelsNetworkTokenizationPayer
     */
    'countryCode': string;
}

