/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Client message type enumeration
 * @export
 * @enum {string}
 */
export type PayToolsSharedModelsMessageType = 'NeverUsed' | 'Authenticated' | 'Rejected' | 'FingerPrintRequired' | 'FingerPrintCompleted' | 'ChallengeRequired' | 'TechnicalProblem' | 'CardNotEnrolled' | 'NoResponse'

