/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsBlAuthenticationThreeDsBrand } from './pay-tools-bl-authentication-three-ds-brand';

/**
 * The 3DS Merchant data to be signed
 * @export
 * @interface PayToolsBlAuthenticationThreeDMerchant
 */
export interface PayToolsBlAuthenticationThreeDMerchant {
    /**
     * Merchant name
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDMerchant
     */
    'mnm': string;
    /**
     * Merchant\'s display name
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDMerchant
     */
    'mds': string;
    /**
     * Merchant\'s Requestor Id suffix
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDMerchant
     */
    'msf': string;
    /**
     * Merchant\'s Country (3-digit ISO 3166-1 numeric)
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDMerchant
     */
    'cnt': string;
    /**
     * Merchant\'s Url
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDMerchant
     */
    'url': string;
    /**
     * List of supported brands
     * @type {Array<PayToolsBlAuthenticationThreeDsBrand>}
     * @memberof PayToolsBlAuthenticationThreeDMerchant
     */
    'brds': Array<PayToolsBlAuthenticationThreeDsBrand>;
}

