/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for Custom Form meta-data retrieval
 * @export
 * @interface PayToolsApiModelsCustomFormMetaModel
 */
export interface PayToolsApiModelsCustomFormMetaModel {
    /**
     * Time the Custom Form was initially created
     * @type {string}
     * @memberof PayToolsApiModelsCustomFormMetaModel
     */
    'creationTime'?: string;
    /**
     * Time the Custom Form was lastly updated
     * @type {string}
     * @memberof PayToolsApiModelsCustomFormMetaModel
     */
    'updateTime'?: string | null;
    /**
     * The Custom Form name. It should be used for referencing the form for management and for usage
     * @type {string}
     * @memberof PayToolsApiModelsCustomFormMetaModel
     */
    'name'?: string | null;
}

