/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The model used to return a valid Jws with a single Token
 * @export
 * @interface PayToolsApiModelsJwsOutputModel
 */
export interface PayToolsApiModelsJwsOutputModel {
    /**
     * The jws (token) value to be used in subsequent card operation methods
     * @type {string}
     * @memberof PayToolsApiModelsJwsOutputModel
     */
    'authToken'?: string | null;
}

