/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * List of to brands and logos
 * @export
 * @interface PayToolsApiModelsTopBrands
 */
export interface PayToolsApiModelsTopBrands {
    /**
     * Top credit card brands for lookup of up to 5 first digits. It covers 90% of the cases
     * @type {Array<{ [key: string]: string; }>}
     * @memberof PayToolsApiModelsTopBrands
     */
    'prefixes'?: Array<{ [key: string]: string; }> | null;
    /**
     * Dictionary of Brand name => brand logo Url
     * @type {{ [key: string]: string; }}
     * @memberof PayToolsApiModelsTopBrands
     */
    'logos'?: { [key: string]: string; } | null;
}

