/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for display a string token, including the clear text
 * @export
 * @interface PayToolsApiModelsStringTokenOutputModel
 */
export interface PayToolsApiModelsStringTokenOutputModel {
    /**
     * The content of the StringToken that was stored in our system
     * @type {string}
     * @memberof PayToolsApiModelsStringTokenOutputModel
     */
    'clearPayload'?: string | null;
    /**
     * Token ID representing the stringToken
     * @type {string}
     * @memberof PayToolsApiModelsStringTokenOutputModel
     */
    'token'?: string | null;
    /**
     * Date and time the string was stored
     * @type {string}
     * @memberof PayToolsApiModelsStringTokenOutputModel
     */
    'createTime'?: string;
}

