/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsSharedModelsMoneyModel } from './pay-tools-shared-models-money-model';

/**
 * Data to be used in 3DS authentication request
 * @export
 * @interface PayToolsBlAuthenticationThreeDsSessionModel
 */
export interface PayToolsBlAuthenticationThreeDsSessionModel {
    /**
     * The name of the stored merchant account
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDsSessionModel
     */
    'merchantAccountName': string;
    /**
     * 
     * @type {PayToolsSharedModelsMoneyModel}
     * @memberof PayToolsBlAuthenticationThreeDsSessionModel
     */
    'amt': PayToolsSharedModelsMoneyModel;
}

