/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for 3DS authentication data
 * @export
 * @interface PayToolsApiModelsThreeDSAuthenticationInputModel
 */
export interface PayToolsApiModelsThreeDSAuthenticationInputModel {
    /**
     * 3ds Version
     * @type {string}
     * @memberof PayToolsApiModelsThreeDSAuthenticationInputModel
     */
    'version': string;
    /**
     * Authentication value
     * @type {string}
     * @memberof PayToolsApiModelsThreeDSAuthenticationInputModel
     */
    'authenticationValue': string;
    /**
     * Electronic Commerce Indicator
     * @type {string}
     * @memberof PayToolsApiModelsThreeDSAuthenticationInputModel
     */
    'eci': string;
    /**
     * transaction ID from the 3D Secure provider
     * @type {string}
     * @memberof PayToolsApiModelsThreeDSAuthenticationInputModel
     */
    'xid': string;
    /**
     * Merchant name
     * @type {string}
     * @memberof PayToolsApiModelsThreeDSAuthenticationInputModel
     */
    'merchantName': string;
}

