/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for Payment Gateway Description
 * @export
 * @interface PayToolsApiModelsPaymentGatewayDescriptionModel
 */
export interface PayToolsApiModelsPaymentGatewayDescriptionModel {
    /**
     * Payment Gateway Description (informational)
     * @type {string}
     * @memberof PayToolsApiModelsPaymentGatewayDescriptionModel
     */
    'description'?: string | null;
    /**
     * The ePayTools internal identifier for this Payment Gateway
     * @type {string}
     * @memberof PayToolsApiModelsPaymentGatewayDescriptionModel
     */
    'name'?: string | null;
    /**
     * The name of the Payment Gateway in friendly format
     * @type {string}
     * @memberof PayToolsApiModelsPaymentGatewayDescriptionModel
     */
    'displayName'?: string | null;
    /**
     * Url to Payment Gateway site (informational)
     * @type {string}
     * @memberof PayToolsApiModelsPaymentGatewayDescriptionModel
     */
    'paymentGatewayUrl'?: string | null;
    /**
     * A list of all credential parameters needed to provide for this Payment Gateway
     * @type {Array<string>}
     * @memberof PayToolsApiModelsPaymentGatewayDescriptionModel
     */
    'credentialsNames'?: Array<string> | null;
    /**
     * Indicates whether the Payment gateway supports Network Token (from Card schemes)
     * @type {boolean}
     * @memberof PayToolsApiModelsPaymentGatewayDescriptionModel
     */
    'supportsNetworkToken'?: boolean;
}

