/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for display a string token meta-data
 * @export
 * @interface PayToolsApiModelsStringTokenMetaDataOutputModel
 */
export interface PayToolsApiModelsStringTokenMetaDataOutputModel {
    /**
     * Token ID representing the stringToken
     * @type {string}
     * @memberof PayToolsApiModelsStringTokenMetaDataOutputModel
     */
    'token'?: string | null;
    /**
     * Date and time the string was stored
     * @type {string}
     * @memberof PayToolsApiModelsStringTokenMetaDataOutputModel
     */
    'createTime'?: string;
}

