/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PciBookingIINLookupLibraryCardValidationResult } from './pci-booking-iinlookup-library-card-validation-result';

/**
 * The model used to return a valid Jws with payload
 * @export
 * @interface PayToolsApiModelsJwsOutputModel1pciBookingIINLookupLibraryCardValidationResultpciBookingIINLookupLibraryVersion1040CultureneutralPublicKeyTokennull
 */
export interface PayToolsApiModelsJwsOutputModel1pciBookingIINLookupLibraryCardValidationResultpciBookingIINLookupLibraryVersion1040CultureneutralPublicKeyTokennull {
    /**
     * 
     * @type {PciBookingIINLookupLibraryCardValidationResult}
     * @memberof PayToolsApiModelsJwsOutputModel1pciBookingIINLookupLibraryCardValidationResultpciBookingIINLookupLibraryVersion1040CultureneutralPublicKeyTokennull
     */
    'payload'?: PciBookingIINLookupLibraryCardValidationResult;
    /**
     * The jws (token) value to be used in subsequent card operation methods
     * @type {string}
     * @memberof PayToolsApiModelsJwsOutputModel1pciBookingIINLookupLibraryCardValidationResultpciBookingIINLookupLibraryVersion1040CultureneutralPublicKeyTokennull
     */
    'authToken'?: string | null;
}

