/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentsCurrencyCode } from './payments-currency-code';

/**
 * Represents an amount in a given currency
 * @export
 * @interface PayToolsSharedModelsMoneyModel
 */
export interface PayToolsSharedModelsMoneyModel {
    /**
     * 
     * @type {PaymentsCurrencyCode}
     * @memberof PayToolsSharedModelsMoneyModel
     */
    'cur': PaymentsCurrencyCode;
    /**
     * Amount
     * @type {number}
     * @memberof PayToolsSharedModelsMoneyModel
     */
    'amt': number;
}

