/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsBlAuthenticationChargePresetData } from './pay-tools-bl-authentication-charge-preset-data';
import { PayToolsSharedModelsCardStoredCard } from './pay-tools-shared-models-card-stored-card';

/**
 * Model for signing a Cvv Operation
 * @export
 * @interface PayToolsBlAuthenticationCvvSignedDataModel
 */
export interface PayToolsBlAuthenticationCvvSignedDataModel {
    /**
     * 
     * @type {PayToolsSharedModelsCardStoredCard}
     * @memberof PayToolsBlAuthenticationCvvSignedDataModel
     */
    'card'?: PayToolsSharedModelsCardStoredCard;
    /**
     * 
     * @type {PayToolsBlAuthenticationChargePresetData}
     * @memberof PayToolsBlAuthenticationCvvSignedDataModel
     */
    'crg_d'?: PayToolsBlAuthenticationChargePresetData;
}

