/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for a Charge request of an existing card after capturing security code (CVV) for card processing via a payment gateway using Card operations
 * @export
 * @interface PayToolsApiModelsCvvOpsChargeRequest
 */
export interface PayToolsApiModelsCvvOpsChargeRequest {
    /**
     * The card details that should be charged. You can either provide us with the raw card details or provide a reference to the stored card details in a token.
     * @type {string}
     * @memberof PayToolsApiModelsCvvOpsChargeRequest
     */
    'cvv': string;
}

