/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsBlAuthenticationChargePresetData } from './pay-tools-bl-authentication-charge-preset-data';
import { PayToolsBlAuthenticationThreeDsPresetData } from './pay-tools-bl-authentication-three-ds-preset-data';
import { PayToolsBlAuthenticationTokenizationAction } from './pay-tools-bl-authentication-tokenization-action';
import { PayToolsSharedEnumsPerform3ds } from './pay-tools-shared-enums-perform3ds';
import { PaymentsChargeRequest } from './payments-charge-request';
import { PaymentsOperationResult } from './payments-operation-result';
import { PciBookingIINLookupLibraryCardValidationRequest } from './pci-booking-iinlookup-library-card-validation-request';
import { PciBookingIINLookupLibraryCardValidationResult } from './pci-booking-iinlookup-library-card-validation-result';
import { PciBookingIINLookupLibraryRiskLevel } from './pci-booking-iinlookup-library-risk-level';

/**
 * Class to represent signed data
 * @export
 * @interface PayToolsBlAuthenticationSignedData
 */
export interface PayToolsBlAuthenticationSignedData {
    /**
     * 
     * @type {PciBookingIINLookupLibraryCardValidationRequest}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'vld_rq'?: PciBookingIINLookupLibraryCardValidationRequest;
    /**
     * 
     * @type {PciBookingIINLookupLibraryCardValidationResult}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'vld_rs'?: PciBookingIINLookupLibraryCardValidationResult;
    /**
     * 
     * @type {PaymentsChargeRequest}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'crg_rq'?: PaymentsChargeRequest;
    /**
     * 
     * @type {PaymentsOperationResult}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'crg_rs'?: PaymentsOperationResult;
    /**
     * Result from tokenization
     * @type {string}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'tkn_rs'?: string | null;
    /**
     * 
     * @type {PayToolsBlAuthenticationThreeDsPresetData}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    '3ds_d'?: PayToolsBlAuthenticationThreeDsPresetData;
    /**
     * 
     * @type {PciBookingIINLookupLibraryRiskLevel}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'vld'?: PciBookingIINLookupLibraryRiskLevel;
    /**
     * Options for performing #DS
     * @type {PayToolsSharedEnumsPerform3ds}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    '3ds'?: PayToolsSharedEnumsPerform3ds;
    /**
     * Is Card charge required for this session
     * @type {boolean}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'crg'?: boolean;
    /**
     * Tokenization Action
     * @type {PayToolsBlAuthenticationTokenizationAction}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'tkn'?: PayToolsBlAuthenticationTokenizationAction;
    /**
     * 
     * @type {PayToolsBlAuthenticationChargePresetData}
     * @memberof PayToolsBlAuthenticationSignedData
     */
    'crg_d'?: PayToolsBlAuthenticationChargePresetData;
}

