/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Options for performing #DS
 * @export
 * @enum {string}
 */
export type PayToolsSharedEnumsPerform3ds = 'Mandatory' | 'Skip' | 'Optional'

