/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsBlAuthenticationThreeDMerchant } from './pay-tools-bl-authentication-three-dmerchant';
import { PayToolsSharedModelsMoneyModel } from './pay-tools-shared-models-money-model';

/**
 * Data to be used in 3DS authentication request
 * @export
 * @interface PayToolsBlAuthenticationThreeDsPresetData
 */
export interface PayToolsBlAuthenticationThreeDsPresetData {
    /**
     * Session Id with MPI
     * @type {string}
     * @memberof PayToolsBlAuthenticationThreeDsPresetData
     */
    'sid'?: string | null;
    /**
     * 
     * @type {PayToolsBlAuthenticationThreeDMerchant}
     * @memberof PayToolsBlAuthenticationThreeDsPresetData
     */
    'mrc'?: PayToolsBlAuthenticationThreeDMerchant;
    /**
     * 
     * @type {PayToolsSharedModelsMoneyModel}
     * @memberof PayToolsBlAuthenticationThreeDsPresetData
     */
    'amt'?: PayToolsSharedModelsMoneyModel;
}

