/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentsCardTypes } from './payments-card-types';

/**
 * 
 * @export
 * @interface PayToolsDalEntitiesThreeDsBrand
 */
export interface PayToolsDalEntitiesThreeDsBrand {
    /**
     * 
     * @type {PaymentsCardTypes}
     * @memberof PayToolsDalEntitiesThreeDsBrand
     */
    'brand'?: PaymentsCardTypes;
    /**
     * 
     * @type {string}
     * @memberof PayToolsDalEntitiesThreeDsBrand
     */
    'bin': string;
    /**
     * 
     * @type {string}
     * @memberof PayToolsDalEntitiesThreeDsBrand
     */
    'merchantId': string;
    /**
     * 
     * @type {string}
     * @memberof PayToolsDalEntitiesThreeDsBrand
     */
    'mcc': string;
}

