/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Model for providing a string to be tokenized
 * @export
 * @interface PayToolsApiModelsStringTokenIntputModel
 */
export interface PayToolsApiModelsStringTokenIntputModel {
    /**
     * The content of the string you would like to tokenize
     * @type {string}
     * @memberof PayToolsApiModelsStringTokenIntputModel
     */
    'payload': string;
}

