/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsApiModelsCardInputModel } from './pay-tools-api-models-card-input-model';
import { PayToolsApiModelsPayerDetailsNoIpAddress } from './pay-tools-api-models-payer-details-no-ip-address';

/**
 * Model for a Charge request for card processing via a payment gateway using Card operations
 * @export
 * @interface PayToolsApiModelsCardOpsChargeRequest
 */
export interface PayToolsApiModelsCardOpsChargeRequest {
    /**
     * 
     * @type {PayToolsApiModelsPayerDetailsNoIpAddress}
     * @memberof PayToolsApiModelsCardOpsChargeRequest
     */
    'payerDetails'?: PayToolsApiModelsPayerDetailsNoIpAddress;
    /**
     * 
     * @type {PayToolsApiModelsCardInputModel}
     * @memberof PayToolsApiModelsCardOpsChargeRequest
     */
    'card': PayToolsApiModelsCardInputModel;
    /**
     * Your custom reference for this transaction
     * @type {string}
     * @memberof PayToolsApiModelsCardOpsChargeRequest
     */
    'myRef'?: string | null;
}

