/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayToolsApiModelsCardInputModel } from './pay-tools-api-models-card-input-model';
import { PayToolsApiModelsPaymentGatewayAccount } from './pay-tools-api-models-payment-gateway-account';
import { PaymentsNetworkTokenSchemes } from './payments-network-token-schemes';

/**
 * Model for a Capturing or voiding a previously Pre-authorize request via a payment gateway
 * @export
 * @interface PayToolsApiModelsCaptureVoidRequestModel
 */
export interface PayToolsApiModelsCaptureVoidRequestModel {
    /**
     * The currency of the transaction. Based on the <a href=\"https://en.wikipedia.org/wiki/ISO_4217#Active_codes\" target=\"_blank\">ISO 4217</a> standard.
     * @type {string}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'currency': string;
    /**
     * The transaction ID that this operation is referring to.
     * @type {string}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'refTransId': string;
    /**
     * 
     * @type {PayToolsApiModelsCardInputModel}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'card': PayToolsApiModelsCardInputModel;
    /**
     * The amount to be charged (the amount should be in major units - for example, 10.23)
     * @type {number}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'amount': number;
    /**
     * Your custom reference for this transaction
     * @type {string}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'myRef'?: string | null;
    /**
     * The reference name provided to the stored Payment Gateway Account as set in `PUT /PaymentGatewayAccounts/{name}`.  **Please note**, if you provide us with both this parameter and the raw credentials in the `paymentGatewayAccount` object, this parameter will be ignored and the raw credentials will take precedence.
     * @type {string}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'paymentGatewayAccountName'?: string | null;
    /**
     * Optional parameter if the payment gateway requires authentication using a client certificate. The name of the certificate that was stored in our system via our <a href=\"https://portal.epaytools.com\" target=\"_blank\">users portal</a>
     * @type {string}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'certificateName'?: string | null;
    /**
     * 
     * @type {PayToolsApiModelsPaymentGatewayAccount}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'paymentGatewayAccount'?: PayToolsApiModelsPaymentGatewayAccount;
    /**
     * 
     * @type {PaymentsNetworkTokenSchemes}
     * @memberof PayToolsApiModelsCaptureVoidRequestModel
     */
    'networkTokenBrand'?: PaymentsNetworkTokenSchemes;
}

