/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The model used to return a valid Jws with multiple tokens
 * @export
 * @interface PayToolsApiModelsJwsMultipleOutputModel
 */
export interface PayToolsApiModelsJwsMultipleOutputModel {
    /**
     * The jws (token) value to be used for 3DS
     * @type {string}
     * @memberof PayToolsApiModelsJwsMultipleOutputModel
     */
    'threeDsAuthToken'?: string | null;
    /**
     * The jws (token) value to be used in subsequent card operation methods
     * @type {string}
     * @memberof PayToolsApiModelsJwsMultipleOutputModel
     */
    'authToken'?: string | null;
}

