/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type PaymentsCardTypes = 'Visa' | 'AMEX' | 'BC' | 'MasterCard' | 'MC_Alaska' | 'MC_Canada' | 'CarteBlanche' | 'UnionPay' | 'Discover' | 'DinersClub' | 'CartaSi' | 'CarteBleue' | 'Dankort' | 'Delta' | 'Electron' | 'JCB' | 'Maestro' | 'Switch' | 'Solo' | 'Lazer' | 'Elo' | 'Hipercard' | 'enRoute' | 'UATP'

