/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentsPayer
 */
export interface PaymentsPayer {
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'cardOwnerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'address1'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'address2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'address3'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'stateProvince'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'postCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'clientIPAddress'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'fullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsPayer
     */
    'validIpAddress'?: string | null;
}

