/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentsThreeDS
 */
export interface PaymentsThreeDS {
    /**
     * 
     * @type {string}
     * @memberof PaymentsThreeDS
     */
    'version'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsThreeDS
     */
    'authenticationValue'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsThreeDS
     */
    'eci'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentsThreeDS
     */
    'xid'?: string | null;
}

