/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentsCurrencyCode } from './payments-currency-code';

/**
 * 
 * @export
 * @interface PaymentsMoney
 */
export interface PaymentsMoney {
    /**
     * 
     * @type {number}
     * @memberof PaymentsMoney
     */
    'amount'?: number;
    /**
     * 
     * @type {PaymentsCurrencyCode}
     * @memberof PaymentsMoney
     */
    'currencyCode'?: PaymentsCurrencyCode;
    /**
     * 
     * @type {string}
     * @memberof PaymentsMoney
     */
    'iso4217CurrencyNumber'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentsMoney
     */
    'amountInLargestUnits'?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentsMoney
     */
    'formattedAmount'?: string | null;
}

