/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentsBankCardBase
 */
export interface PaymentsBankCardBase {
    /**
     * 
     * @type {string}
     * @memberof PaymentsBankCardBase
     */
    'number'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentsBankCardBase
     */
    'expirationMonth'?: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentsBankCardBase
     */
    'expirationYear'?: number;
}

