/*
Orchestra API

Code Version 1.0.7.15

The version of the OpenAPI document: Prod


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PciBookingIINLookupLibraryCardValidationRequest
 */
export interface PciBookingIINLookupLibraryCardValidationRequest {
    /**
     * 
     * @type {string}
     * @memberof PciBookingIINLookupLibraryCardValidationRequest
     */
    'iin'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PciBookingIINLookupLibraryCardValidationRequest
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PciBookingIINLookupLibraryCardValidationRequest
     */
    'stateProvince'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PciBookingIINLookupLibraryCardValidationRequest
     */
    'countryCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PciBookingIINLookupLibraryCardValidationRequest
     */
    'clientIPAddress'?: string | null;
}

